[package]
name = "rock-paper-scissors"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.16.1"
itertools = "0.14.0"
rand = "0.9.2"
